version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "datanative"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m7qzku3nybi3"
s3_prefix = "datanative"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
